blank_issues_enabled: false
contact_links:
  - name: Homebridge Discord
    url: https://discord.gg/7X36mdw
    about: The Homebridge Discord is a community where you can ask questions and get general help with Homebridge and plugins. You can also message me directly on there - my username is bwp91.
